import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CartProvider from "@/data/context/cart-context";
import ProductProvider from "@/data/context/product-context";
import PaymentProvider from "@/data/context/payment-context";


export const metadata: Metadata = {
  title: "E-acai",
  description: "Generated by create next app",
};

const font = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <ProductProvider>
        <CartProvider>
          <PaymentProvider>
            <body className={`${font.className} antialiased`}>{children}</body>
          </PaymentProvider>
        </CartProvider>
      </ProductProvider>
    </html>
  );
}
